### ISSUE TITLE
Duplicated scope, incompatibility

### ISSUE THREAD

**Issue by toboter** [jrochkind/json_attribute#10]
I'm experimenting a bit with this great gem. When I query:

MyModel.jsonb_contains (payload: {string_id: 'id'})

The following error message is raised:
ArgumentError: You tried to define a scope named "jsonb_contains" on the model "MyModel", but ActiveRecord already defined a class method with the same name.

 I've also defined 'jsonb_accessor' in gemfile. If I remove that, the query works fine.

**Comment by jrochkind** [comment]
Thanks for taking it for a spin and giving feedback!

It looks like this gem is incompatible with the `jsonb_accessor` gem, as they both try to define a `jsonb_contains` scope. I could potentially make the scope name `jsonb_contains` configurable, so you can choose to name the one from this gem something else to avoid conflicts. 

But what is your motivation in trying to use both this and `jsonb_accessor` at once, do you actually need both?

Thanks!

**Comment by jrochkind** [comment]
I could also give you a workaround where you can rename the `jsonb_contains` scope something else yourself in your app, with the gem as it is. 

But I suspect nobody actually needs both (in the same model anyway), the two gems are basically alternatives.

**Comment by jrochkind** [comment]
Also I've never seen the name "ActiveRock" before, and it does not appear to be from `jsonb_accessor`. Probably does not matter for this issue, but just curious, do you recognize that, do you know where it's from?  Googling I'm not having much luck.

**Comment by toboter** [comment]
No motivation at all. I was just testing and for a short moment a little bit confused and just wanted to share my confusion. Rookie question: Won't that raise any errors if you use an engine that depends on jsonb_accessor and you are using this gem for the main app? Why is it called jsonb_contains? Why not 'jsonb_column_name'_contains?

Hehe, funny. ActiveRock! That was a copy-paste translation mistake.

**Comment by jrochkind** [comment]
This gem, unlike `jsonb_accessor` doesn't monkey-patch ActiveRecord at all. It would be nice if jsonb_accessor didn't either, at least not automatically. 

It won't neccesarily cause problems if you have jsonb_accessor as a second-level dependency, because second-(and-further-)level dependencies aren't normally automatically "require"d. But it will cause problems as soon as anything `require 'jsonb_accessor'`.  (Are there engines that depend on jsonb_accessor? Curious to see them). 

I think `jsonb_contains` is the right name -- and I don't want callers to have to know what host jsonb columns include the json_attribute when making the call -- but the functionality here is only present in a model if you explicitly `include JsonAttribute::Record::QueryScopes`.  So you could use this gem in an app with `jsonb_accessor` if you don't do that. But if you want the functionality, and you have a `jsonb_accessor` as a dependency, there's a simple workaround. 

1. Don't include `JsonAttribute::Record::QueryScope` in your model(s). 

2. Instead, make your _own_ module that looks a lot like `JsonAttribute::Record::QueryScope` (it's essentially just one line!), but chooses a different name for the scope, and include that. Like so:

```ruby
module MyCustomQueryScopes
      extend ActiveSupport::Concern

      included do
        unless self < JsonAttribute::Record
          raise TypeError, "JsonAttribute::Record::QueryScopes can only be included in a JsonAttribute::Record"
        end

        scope(:non_conflicting_jsonb_contains, lambda do |attributes|
          QueryBuilder.new(self, attributes).contains_relation
        end)
      end
    end
```

Alternately, ask the author of jsonb_accessor to make adding the query scope to all ActiveRecord::Base models to be opt-in or opt-out-able, instead of automatic with no way to turn it off.
